### ISSUE TITLE
Compatibility with aeson-1.x

### ISSUE THREAD

**Issue by themoritz** [eskimor/purescript-argonaut-generic-codecs#10]
This package is not compatible with aeson-1.x, at least because of https://github.com/bos/aeson/pull/307, which ended up in 1.0.0.0 and is now in lts-8.0.

Should the goal of this repo be to mirror the generic instances of aeson? If yes, I can try to prepare a PR.

**Comment by themoritz** [comment]
Ah I just noticed there are aeson and argonaut specific options. So I guess the aeson version should be updated.

**Comment by eskimor** [comment]
Hi themoritz! If aeson changed it's default encoding format (which is pretty nasty!) then yes, we should adjust this library. If you could help out there, this would be much appreciated! Thank you!
