### ISSUE TITLE
pursuit link down?

### ISSUE THREAD

**Issue by mmaz** [eskimor/purescript-argonaut-generic-codecs#19]
This is one of my favorite PureScript projects (especially the great support for Aeson), thanks for authoring it! The [Pursuit docs](https://pursuit.purescript.org/packages/purescript-argonaut-generic-codecs) currently seem to be broken; did the travis build fall over?

**Comment by eskimor** [comment]
Well I should set up travis at some point :-P I fixed it manually for now. Glad you like it! :-)
