### ISSUE TITLE
aeson option differs from haskell's one

### ISSUE THREAD

**Issue by akegalj** [eskimor/purescript-argonaut-generic-codecs#3]
Documentation https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/purescript-argonaut-generic-codec/src/Data/Argonaut/Generic/Aeson.purs#L50 states that options are compatible with `aeson` default options which doesn't seem to be a case: `unwrapUnaryRecords` differs (https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/purescript-argonaut-generic-codec/src/Data/Argonaut/Generic/Aeson.purs#L50 , https://hackage.haskell.org/package/aeson-0.11.2.0/docs/Data-Aeson-Types.html#v:defaultOptions)

**Comment by eskimor** [comment]
That puzzled me too, in fact previous versions of purescript-argonaut-generic-codecs had this option disabled because of this. But it seems to be a bug in aeson, that despite the fact that the option is disabled by default the unwrapping takes place - you can test this easily in ghci. I haven't found the time yet to investigate that more, but it seems to be a bug in aeson and probably should be reported.

So you are correct the options differ (most likely due to a bug in aeson) but the behaviour is the same.

**Comment by akegalj** [comment]
Yes, we were trying to deal with `aeson` bug the whole day now. Thank you, we will most likely report the bug to `aeson` (I will put reference here when we do)

EDIT: I see that you already have reported the bug, thanks. We will most likely put some examples that show this.

**Comment by eskimor** [comment]
That would be nice thank you! I am currently on holiday - I will release a current version of purescript-bridge when I am back.

**Comment by gromakovsky** [comment]
I think there is no bug in aeson. Can you please provide an example of bug when you have time?

**Comment by eskimor** [comment]
Just use generic encoding with default options on something like

``` haskell
data Test = Test Int deriving (Generic)
instance ToJSON Test
```

``` haskell
encode $ Test 5
```

will result in 5 not in 

``` javascript
{ tag: "Test", contents: 5}
```

thus unwrapUnaryRecords is enabled, although the default option says otherwise.

Sorry if this code does not compile - my laptop just got stolen and I don't have a dev environment yet.

**Comment by eskimor** [comment]
@gromakovsky you were right - there is no bug in aeson. I misunderstood the option - see my comment on the issue there. I will fix this library accordingly!

**Comment by gromakovsky** [comment]
@eskimor alright. @akegalj misunderstood this option too.

**Comment by eskimor** [comment]
@gromakovsky it is good, not to be alone with this ;-)
