### ISSUE TITLE
Document how to run the test-suite

### ISSUE THREAD

**Issue by soenkehahn** [eskimor/purescript-argonaut-generic-codecs#7]
It'd be nice (for being able to hack on the library) if the README had clear instructions on how to install all test dependencies and how to run the test-suite.

(I wanted to verify whether #6 is fixed, but I can't get the tests to run currently.)

**Comment by eskimor** [comment]
Uhhh - ok- i'll see what needs to be done. (They run for me.) To answer your question - yep, it is fixed. All tests pass.

**Comment by eskimor** [comment]
(On master - new release coming soon, but I want to add another test case first)

**Comment by eskimor** [comment]
Hmm - what problems are you facing. A simple bower install && pulp test works for me. - I'll put that in the readme. Also I just hit a quickcheck error, so it might take a little longer to the next release.

**Comment by soenkehahn** [comment]
Yeah, the change to the README that you made were exactly what I needed. I'm new to purescript and I tried `npm install` instead of `bower install`. Thanks a lot.

**Comment by eskimor** [comment]
Well, welcome to PureScript then!
